apiVersion: v1
kind: Service
metadata:
  name: {{ include "prism.fullname" . }}-proxy
  labels:
    {{- include "prism.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
spec:
  type: {{ .Values.proxy.service.type }}
  selector:
    {{- include "prism.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  ports:
    - name: proxy
      port: {{ .Values.proxy.listenPort }}
      targetPort: {{ .Values.proxy.listenPort }}
      protocol: TCP
    - name: api
      port: {{ .Values.proxy.apiPort }}
      targetPort: {{ .Values.proxy.apiPort }}
      protocol: TCP
